title: "Oliver Wunsch"
description: "Academic website for Oliver Wunsch"
url: "https://owunsch.github.io"
baseurl: ""
markdown: kramdown
permalink: pretty

collections:
  articles:
    output: true
    permalink: /articles/:slug/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: articles
    values:
      layout: article

site_owner:
  name: "Oliver Wunsch"
  affiliation: "Boston College"
  email: "wunscho@bc.edu"

home_intro:
  short_blurb: >
    I'm an art historian at Boston College focusing on eighteenth- and nineteenth-century European art. I mostly use this site to share PDFs of my work.
book:
  title: "A Delicate Matter: Art, Fragility, and Consumption in Eighteenth-Century France"
  year: 2024
  publisher: "Pennsylvania State University Press"
  status: "published"
  citation_display: "Oliver Wunsch, *A Delicate Matter: Art, Fragility, and Consumption in Eighteenth-Century France* (Pennsylvania State University Press, 2024)."
  description: >-
    *A Delicate Matter: Art, Fragility, and Consumption in Eighteenth-Century France* examines how fragile media such as pastels, terracottas, and even oil paintings prone to cracking, became prized commodities in a burgeoning eighteenth-century art market. I argue that commercial modernityâ€™s embrace of ephemerality created the conditions for artists to experiment with unstable materials and techniques as never before. In the process, artists turned fragility from a liability into a resource, transforming the instability of consumer goods into a vehicle for evanescent forms of subjective expression. By investing fragility itself with expressive power, they sought to distinguish the flimsiness of disposable commodities from the exalted delicacy of transcendent art.
  links:
    publisher: ""
    amazon: ""
    worldcat: ""
    other: []
